/* Auto-extracted from the original verified product list. */
(function () {
  'use strict';
  window.VC_PRODUCTS = [
    { id: 'p1', cat: 'spec', name: 'Sodium Metabisulphite', grade: 'Technical 97%', app: 'Dechlorination, preservation and reduction processes.', specs: ['97%', 'Powder', '25kg'], div: 'spec' },
    { id: 'p2', cat: 'spec', name: 'Sodium Bicarbonate', grade: 'Food/Feed 99.5%', app: 'Baking, feed, flue-gas treatment and pH buffering.', specs: ['99.5%', 'Powder', '25kg'], div: 'spec' },
    { id: 'p3', cat: 'spec', name: 'Sodium Benzoate', grade: 'Food E211', app: 'Preservative for beverages and food processing.', specs: ['99%', 'Powder', '25kg'], div: 'spec' },
    { id: 'p4', cat: 'spec', name: 'Glycerine 99.5%', grade: 'USP/BP', app: 'Humectant for pharma, cosmetics and personal care.', specs: ['99.5% USP', 'Liquid', '250kg'], div: 'spec' },
    { id: 'p5', cat: 'spec', name: 'EDTA 2Na / 4Na', grade: 'Technical 99%', app: 'Chelating agent for cleaning, water and industry.', specs: ['99%', 'Powder', '25kg'], div: 'spec' },
    { id: 'p6', cat: 'spec', name: 'Zinc Sulphate 33%', grade: 'Agri/Tech', app: 'Zinc correction and micronutrient blending.', specs: ['Zn 33%', 'Powder', '25kg'], div: 'spec' },
    { id: 'p7', cat: 'spec', name: 'Magnesium Sulphate', grade: 'Tech/Agri', app: 'Epsom salt for crops and process industries.', specs: ['MgSO4', 'Crystal', '25kg'], div: 'spec' },
    { id: 'p8', cat: 'ind', name: 'Caustic Soda Flakes', grade: 'Industrial 99%', app: 'Sodium hydroxide for soap, textiles, paper, alumina.', specs: ['NaOH 99%', 'Flakes', '25/50kg'], div: 'ind' },
    { id: 'p9', cat: 'ind', name: 'Caustic Soda Pearls', grade: 'Industrial 99%', app: 'Low-dust pearls for detergents and dosing.', specs: ['NaOH 99%', 'Pearls', '25kg'], div: 'ind' },
    { id: 'p10', cat: 'ind', name: 'Soda Ash Dense', grade: '99.2%', app: 'Glass, detergent and metallurgical workhorse.', specs: ['Na2CO3 99.2%', 'Powder', '50kg/1MT'], div: 'ind' },
    { id: 'p11', cat: 'ind', name: 'Soda Ash Light', grade: '99.2%', app: 'Fine grade for chemicals and detergents.', specs: ['Na2CO3 99.2%', 'Fine', '40kg'], div: 'ind' },
    { id: 'p12', cat: 'ind', name: 'Hydrated Lime', grade: 'Technical', app: 'Neutralization, effluent treatment and construction.', specs: ['Ca(OH)2 90%', 'Powder', '50kg'], div: 'ind' },
    { id: 'p13', cat: 'ind', name: 'Urea N46 Prilled', grade: 'Agri/Industrial', app: 'High-nitrogen fertilizer and industrial resin use.', specs: ['N 46%', 'Prills', '50kg/1MT'], div: 'ind' },
    { id: 'p14', cat: 'ind', name: 'DAP 18-46-0', grade: 'Agri Grade', app: 'Basal N+P nutrition for crops.', specs: ['18-46-0', 'Granular', '50kg'], div: 'ind' },
    { id: 'p15', cat: 'ind', name: 'MOP K60', grade: 'Potash', app: 'Potassium for fruit, starch and plantation crops.', specs: ['K2O 60%', 'Granular', '50kg'], div: 'ind' },
    { id: 'p16', cat: 'ind', name: 'Hydrochloric Acid', grade: '30-33%', app: 'Pickling, descaling and acidizing applications.', specs: ['30-33%', 'Liquid', 'IBC'], div: 'ind' },
    { id: 'p17', cat: 'ind', name: 'Sulphuric Acid 98%', grade: 'Technical', app: 'Fertilizer, synthesis and metal processing.', specs: ['98%', 'Liquid', 'IBC'], div: 'ind' },
    { id: 'p18', cat: 'ind', name: 'Nitric Acid 68%', grade: 'Technical', app: 'Etching, intermediates and fertilizer grades.', specs: ['68%', 'Liquid', 'Carboys'], div: 'ind' },
    { id: 'p19', cat: 'ind', name: 'Phosphoric Acid 85%', grade: 'Food/Tech', app: 'Beverage acidulant and fertilizer salts.', specs: ['85%', 'Liquid', 'IBC'], div: 'ind' },
    { id: 'p20', cat: 'ind', name: 'Methanol 99.85%', grade: 'Technical', app: 'Formaldehyde, biodiesel and solvent uses.', specs: ['99.85%', 'Liquid', '200L'], div: 'ind' },
    { id: 'p21', cat: 'ind', name: 'Acetone', grade: 'Technical 99.5%', app: 'Fast solvent for resins, inks and cleaning.', specs: ['99.5%', 'Liquid', 'Drums'], div: 'ind' },
    { id: 'p22', cat: 'ind', name: 'Formaldehyde 37%', grade: 'Industrial', app: 'Resin and plywood intermediate.', specs: ['37%', 'Liquid', 'Drums'], div: 'ind' },
    { id: 'p23', cat: 'ind', name: 'PAC 30%', grade: 'Coagulant', app: 'Coagulant for turbidity removal in water plants.', specs: ['Al2O3 30%', 'Powder', '25kg'], div: 'ind' },
    { id: 'p24', cat: 'ind', name: 'Aluminium Sulphate', grade: '17% Non-Ferric', app: 'Clarification for municipal water plants.', specs: ['17%', 'Powder', '50kg'], div: 'ind' },
    { id: 'p25', cat: 'con', name: 'PCE Superplasticizer', grade: 'High Range', app: 'Polycarboxylate admixture for high-flow concrete.', specs: ['Liquid 40%', '200L', 'RMC Grade'], div: 'con' },
    { id: 'p26', cat: 'con', name: 'SNF Powder', grade: 'Conplast Grade', app: 'Sulphonated naphthalene water reducer.', specs: [' Powder', '25kg', 'Construction'], div: 'con' },
    { id: 'p27', cat: 'con', name: 'Concrete Curing Compound', grade: 'Wax Emulsion', app: 'Moisture retention film for fresh concrete.', specs: ['30% solids', '200L', 'Spray-on'], div: 'con' },
    { id: 'p28', cat: 'con', name: 'Integral Waterproofing', grade: 'Admixture', app: 'Water-resistant concrete and plaster admixture.', specs: ['Liquid', '200L', 'IS 2645'], div: 'con' },
    { id: 'p29', cat: 'con', name: 'Tile Adhesive', grade: 'C2TE Grade', app: 'Cement-based adhesive for tile and stone.', specs: ['EN 12004', '25kg', 'Grey/White'], div: 'con' },
    { id: 'p30', cat: 'con', name: 'Epoxy Grout', grade: 'High Strength', app: 'Chemical-resistant grout for joints and fixings.', specs: ['3-part', 'Kit', 'Industrial'], div: 'con' },
    { id: 'p31', cat: 'con', name: 'Floor Hardener', grade: 'Metallic/NM', app: 'Abrasion-resistant topping for industrial floors.', specs: ['Dry shake', '25kg', 'Warehouse'], div: 'con' },
    { id: 'p32', cat: 'con', name: 'Mould Release Oil', grade: 'Premium', app: 'Release agent for precast and formwork.', specs: ['Emulsion', '200L', 'Construction'], div: 'con' },
    { id: 'p33', cat: 'hc', name: 'IPA 99.9%', grade: 'Pharma/USP', app: 'High-purity isopropyl alcohol for sterile cleaning.', specs: ['99.9%', 'Liquid', '200L'], div: 'hc' },
    { id: 'p34', cat: 'hc', name: 'Glycerine USP', grade: 'Pharma', app: 'Pharmacopeia-grade humectant for formulations.', specs: ['99.5% USP', 'Liquid', '250kg'], div: 'hc' },
    { id: 'p35', cat: 'hc', name: 'BKC 80%', grade: 'Disinfectant', app: 'Quaternary ammonium disinfectant for hospitals.', specs: ['BKC 80%', 'Liquid', '200kg'], div: 'hc' },
    { id: 'p36', cat: 'hc', name: 'Hydrogen Peroxide', grade: '35/50%', app: 'Oxidizing disinfectant for sterile environments.', specs: ['35/50%', 'Liquid', 'Carboys'], div: 'hc' },
    { id: 'p37', cat: 'hc', name: 'Chloroxylenol PCMX', grade: 'Antiseptic', app: 'Active for antiseptic liquids and handwash.', specs: ['PCMX 99%', 'Powder', '25kg'], div: 'hc' },
    { id: 'p38', cat: 'hc', name: 'Potassium Permanganate', grade: 'Technical', app: 'Oxidizer for water treatment and antiseptic use.', specs: ['99%', 'Crystal', '25kg/50kg'], div: 'hc' },
    { id: 'p39', cat: 'hc', name: 'Surgical Spirit BP', grade: 'IP/BP', app: 'Rubbing alcohol for clinical application.', specs: ['BP Grade', 'Liquid', '5/50L'], div: 'hc' },
    { id: 'p40', cat: 'cln', name: 'LABSA 96%', grade: 'Detergent Grade', app: 'Anionic surfactant backbone for detergents.', specs: ['96% active', 'Liquid', '210kg drums'], div: 'cln' },
    { id: 'p41', cat: 'cln', name: 'SLES 70%', grade: 'Detergent Grade', app: 'Foaming surfactant for shampoos and cleaners.', specs: ['70% active', 'Paste', '170kg drums'], div: 'cln' },
    { id: 'p42', cat: 'cln', name: 'SLS Powder', grade: '92% active', app: 'Foaming agent for toothpaste and powders.', specs: ['92% active', 'Powder', '25kg'], div: 'cln' },
    { id: 'p43', cat: 'cln', name: 'CAPB 30%', grade: 'Cosmetic Grade', app: 'Mild amphoteric for shampoos and handwash.', specs: ['30% active', 'Liquid', '200kg'], div: 'cln' },
    { id: 'p44', cat: 'cln', name: 'BKC 50%', grade: 'Disinfectant', app: 'Quaternary disinfectant for floors and surfaces.', specs: ['BKC 50%', 'Liquid', '200kg'], div: 'cln' },
    { id: 'p45', cat: 'cln', name: 'HD Degreaser Conc.', grade: 'Industrial', app: 'Alkaline degreaser for auto and engineering.', specs: ['Concentrate', 'Liquid', '50/200L'], div: 'cln' },
    { id: 'p46', cat: 'cln', name: 'Floor Cleaner Conc.', grade: 'Institutional', app: 'Pine/lemon daily mopping concentrate.', specs: ['Concentrate', 'Liquid', '5/50L'], div: 'cln' },
    { id: 'p47', cat: 'cln', name: 'Toilet Cleaner', grade: 'Acidic 10%', app: 'Thickened acid cleaner for scale and stains.', specs: ['10% acid', 'Liquid', '5L/50L'], div: 'cln' },
    { id: 'p48', cat: 'cln', name: 'Phenolic Disinfectant', grade: 'Hospital Grade', app: 'Black/white phenyl for wards and drains.', specs: ['Pine/black', 'Liquid', '5/50L'], div: 'cln' },
    { id: 'p49', cat: 'og', name: 'Barite API', grade: 'Drilling Grade', app: 'Weighting agent for drilling muds.', specs: ['SG 4.2', 'Powder', '50kg/1MT'], div: 'og' },
    { id: 'p50', cat: 'og', name: 'Calcium Chloride', grade: '74-94%', app: 'Brine, dust control and drilling fluid additive.', specs: ['74/94%', 'Prills', '25/50kg'], div: 'og' },
    { id: 'p51', cat: 'og', name: 'Xanthan Gum', grade: 'Drilling Grade', app: 'Viscosifier for oilfield drilling fluids.', specs: ['80 mesh', '25kg', 'API 13A'], div: 'og' },
    { id: 'p52', cat: 'og', name: 'Potassium Chloride', grade: 'Drilling/Agri', app: 'KCl for shale inhibition and clear brines.', specs: ['KCl 95%', 'Granular', '50kg'], div: 'og' },
    { id: 'p53', cat: 'og', name: 'Soda Ash Drilling', grade: 'API Grade', app: 'pH control and calcium removal in muds.', specs: ['Na2CO3 99.2%', 'Powder', '50kg'], div: 'og' },
    { id: 'p54', cat: 'og', name: 'Defoamer', grade: 'Silicone/Oil', app: 'Foam control for mud systems and process.', specs: ['Emulsion', '50/200L', 'Industrial'], div: 'og' },
    { id: 'p55', cat: 'og', name: 'Corrosion Inhibitor', grade: 'Oilfield', app: 'Protection for pipelines and downhole tools.', specs: ['Film forming', '200L', 'Oil soluble'], div: 'og' },
    { id: 'p56', cat: 'og', name: 'CMC / PAC-LV', grade: 'Fluid Loss', app: 'Filtration control for water-based muds.', specs: ['LV grade', '25kg', 'API'], div: 'og' },
    { id: 'p57', cat: 'mar', name: 'Tank Cleaner', grade: 'Marine', app: 'Cargo tank cleaning for chemical and product tankers.', specs: ['Emulsifying', '200L', 'IMO friendly'], div: 'mar' },
    { id: 'p58', cat: 'mar', name: 'Cargo Hold Cleaner', grade: 'Bulk Carriers', app: 'Hold cleaning for coal, cement and grain trades.', specs: ['Alkaline', '200L', 'Low foam'], div: 'mar' },
    { id: 'p59', cat: 'mar', name: 'Marine Descaler', grade: 'Inhibited', app: 'Scale removal from coolers, condensers and pipes.', specs: ['Inhibited acid', '20/200L', 'Safe on metals'], div: 'mar' },
    { id: 'p60', cat: 'mar', name: 'DEHA Oxygen Scavenger', grade: 'Boiler', app: 'Oxygen scavenger for marine boiler feed water.', specs: ['DEHA based', '25/200L', 'Volatile'], div: 'mar' },
    { id: 'p61', cat: 'mar', name: 'Boiler Water Treatment', grade: 'Combo', app: 'Phosphate-polymer programme for aux boilers.', specs: ['Alkaline', '25kg', 'SS safe'], div: 'mar' },
    { id: 'p62', cat: 'mar', name: 'Marine Deck Cleaner', grade: 'All Purpose', app: 'Deck, bulkhead and superstructure cleaning.', specs: ['Concentrate', '5/200L', 'Biodegradable'], div: 'mar' },
    { id: 'p63', cat: 'mar', name: 'Calcium Hypochlorite 65%', grade: 'Granular', app: 'Disinfection for ballast, potable and hatch areas.', specs: ['65% Cl2', 'Granular', '45kg'], div: 'mar' },
    { id: 'p64', cat: 'mar', name: 'Sodium Hypochlorite', grade: '12-15%', app: 'Ballast and MBRS disinfection, ETP dosing.', specs: ['12-15%', 'Liquid', '200L'], div: 'mar' },
    { id: 'p65', cat: 'mar', name: 'Rust Remover / Passivator', grade: 'Marine', app: 'Rust conversion and passivation for deck machinery.', specs: ['Phosphoric', '20L', 'Non-fuming'], div: 'mar' },
    { id: 'p66', cat: 'mar', name: 'Fuel Treatment', grade: 'Combustion', app: 'Fuel stability and combustion improvement additive.', specs: ['Organic', '200L', 'IMO 2020'], div: 'mar' },
  ];
})();
